#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# Export credentials (optional, since now in .env)
export DB_USERNAME=root
export DB_PASSWORD=Maromau31!!

PHP_CS_FIXER_IGNORE_ENV=1 vendor/bin/php-cs-fixer fix --using-cache=no
# Force testing env
php artisan test --env=testing